### ISSUE TITLE
How do you run it?

### ISSUE THREAD

**Issue by TomiLikesToCode** [jack3898/ai-sponge-web#1]

**Comment by jack3898** [comment]
It's barely started! You won't be impressed 🤣 At the moment it's just this
![image](https://github.com/jack3898/ai-sponge-web/assets/28375223/68b0022c-a37e-4bc5-b79c-550f83c09198)
with patrick and spongebob spinning

But if you're really eager to see that then to set up you do:
- download node.js v18 from nodejs.org
- git clone this repository
- run npm install in the project root
- run npm run dev
- go to localhost:5173

**Comment by jack3898** [comment]
I thought I would provide an update on this project, I have made lots of progress with it, with a guide in the README and the characters now talk

https://github.com/jack3898/ai-sponge-web/wiki/Current-preview

**Comment by jack3898** [comment]
I also have the characters mouth movements on the horizon! I will try my best to recreate them similar to ai_sponge!
